# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='shortest_distance',
            new_name='lowest_points',
        ),
    ]
